[package]
name = "nur_core"
description.workspace = true
readme.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
argon2 = "0.6"
axum = { version = "0.8", features = ["multipart", "macros"] }
axum-extra = { version = "0.12", features = ["query"] }
async-stream = "0.3"
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
    "serde",
] }
clap = { version = "4", features = ["derive", "env"] }
colored = "3"
derive_more = { version = "2", features = ["display"] }
html_parser = "0.7"
image = { version = "0.25", default-features = false, features = [
  "avif", "gif", "jpeg", "png", "webp", "rayon"
] }
inquire = "0.9"
jsonwebtoken = { version = "11", default-features = false, features = ["rust_crypto"] }
lazy-limit = "1"
lettre = { version = "0.11", default-features = false, features = [
  "builder", "smtp-transport", "tokio1-rustls-tls"
] }
libwebp-sys = "0.14"
markdown = { version = "1", features = ["serde"] }
mime_guess = "2"
moka = { version = "0.12", default-features = false, features = ["sync"] }
protect-axum = "0.2"
rand = "0.10"
real = { version = "0.1", features = ["axum"] }
regex = "1"
sanitize-filename = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
sha2 = "0.11"
strum = "0.28"
strum_macros = "0.28"
sqlformat = "0.5"
sqlx = { version = "0.9", default-features = false, features = [
  "runtime-tokio", "tls-rustls", "postgres", "chrono", "json", "macros", "migrate", "sqlx-toml"
] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
ts-rs = { version = "12", features = [
    "chrono-impl",
    "no-serde-warnings",
    "serde-json-impl",
] }
uuid = { version = "1.18", features = ["v4"] }
voca_rs = "1.15"
