// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";
import type { JsonValue } from "./serde_json/JsonValue";

export type AuthRole = { id?: number, name: Role, total_count?: bigint | null, };

export type AuthUser = { id?: number, email?: string, username?: string, first_name?: string, last_name?: string, password?: string, role_id?: number, created_at?: string | null, updated_at?: string | null, last_login?: string | null, };

export type ContentAuthor = { id?: number, first_name?: string, last_name?: string, slug?: string, bio?: string | null, media_id?: number | null, created_at?: string | null, updated_at?: string | null, total_count?: bigint | null, };

export type ContentCategory = { id?: number, group_id?: number, locale_id?: number, name?: string, slug?: string, media_id?: string | null, total_count?: bigint | null, };

export type ContentEntry = { id?: number, group_id?: number | null, locale_id?: number, type_id?: number, slug?: string, title?: string, description?: string, text?: string, status?: string, created_by?: number, updated_by?: number, created_at?: string | null, updated_at?: string | null, total_count?: bigint | null, };

export type ContentMeta = { id?: number, entry_id?: number, data?: JsonValue | null, start_time?: string | null, end_time?: string | null, total_count?: bigint | null, };

export type ContentTag = { id?: number, group_id?: number, locale_id?: number, name?: string, slug?: string, total_count?: bigint | null, };

export type ContentType = { id?: number, name?: string, slug?: string, total_count: bigint | null, };

export type Locale = { id?: number, code?: string, name?: string, tsv_dict?: string, total_count?: bigint | null, };

export type Media = { id?: number, alt?: string | null, filename?: string, path?: string, type?: string | null, uploaded_by?: number | null, created_at?: string | null, total_count?: bigint | null, };

export type MediaVariant = { id?: number, media_id?: number, resolution?: number, format?: string, filename?: string, total_count?: bigint | null, };
