// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputType } from "./OutputType";

export type QueryObj<T> = { path: string, query: string, limit: bigint, offset: bigint, ordering: string, type: string | null, search: string | null, id: number | null, locale: string | null, slug: string | null, status: string | null, author: number | null, output_type: OutputType | null, group_id: number | null, start_time: string | null, end_time: string | null, created_after: string | null, created_before: string | null, fields: Array<T>, };

/**
 * Response object:
 * - gives total amount of items
 * - if there is more then limit restricted, provide a link for the next request
 * - if possible, provide a previous link
 * - gives the actual result
 */
export type RespondObj<T> = { count: bigint, next: string | null, previous: string | null, results: Array<T>, };
