// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputType } from "./OutputType";

export type QueryObj<T> = { path: string, query: string, limit: bigint, offset: bigint, ordering: string, type_slug: string | null, tag_slug: string | null, author_slug: string | null, category_slug: string | null, locale_code: string | null, type_id: number | null, media_type: Array<string> | null, entry_id: number | null, character_limit: number | null, search: string | null, id: number | null, locale_id: number | null, slug: string | null, status: string | null, exclude_types: Array<number> | null, output_type: OutputType | null, last_login: boolean, group_id: number | null, grouped: boolean, start_time: string | null, end_time: string | null, created_after: string | null, created_before: string | null, fields: Array<T>, blocks_limit: number | null, blocks_random: boolean, };

/**
 * Response object:
 * - gives total amount of items
 * - if there is more then limit restricted, provide a link for the next request
 * - if possible, provide a previous link
 * - gives the actual result
 */
export type RespondObj<T> = { count: bigint, next: string | null, previous: string | null, results: Array<T>, };
