// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response object:
 * - gives total amount of items
 * - if there is more then limit restricted, provide a link for the next request
 * - if possible, provide a previous link
 * - gives the actual result
 */
export type RespondObj<T> = { count: bigint, next: string | null, previous: string | null, results: Array<T>, };
