// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthRole } from "./models.d";
import type { JsonValue } from "./serde_json/JsonValue";

export type AuthUserSerializer = { id?: number | null, email?: string | null, username?: string | null, first_name?: string | null, last_name?: string | null, password?: string | null, role_id?: number | null, role?: AuthRole | null, created_at?: string | null, updated_at?: string | null, last_login?: string | null, };

export type AuthorSerializer = { id?: number | null, first_name?: string | null, last_name?: string | null, slug?: string | null, bio?: string | null, media_id?: number | null, media?: MediaSerializer | null, };

export type ContentAuthorFacet = { first_name: string, last_name: string | null, slug: string, count: number, };

export type ContentCategoryFacet = { name: string, slug: string, count: number, };

export type ContentCategorySerializer = { id?: number | null, group_id?: number | null, locale_id?: number | null, name?: string | null, slug?: string | null, status?: string | null, media_id?: number | null, media?: MediaSerializer | null, group_members?: Array<GroupMemberSerializer>, };

export type ContentEntryFacets = { categories: Array<ContentCategoryFacet>, tags: Array<ContentTagFacet>, authors: Array<ContentAuthorFacet>, locales: Array<LocaleFacet>, };

export type ContentEntrySerializer = { id?: number | null, group_id?: number | null, category_id?: number | null, locale_id?: number | null, media_id?: number | null, slug?: string | null, status?: string | null, authors?: Array<AuthorSerializer>, meta?: ContentMetaSerializer | null, category?: ContentCategorySerializer | null, type?: ContentTypeSerializer | null, tags?: Array<ContentTagSerializer>, title?: string | null, nodes?: Array<NodeSerializer>, media?: MediaSerializer | null, created_at?: string | null, updated_at?: string | null, group_members?: Array<GroupMemberSerializer>, comment_count?: bigint | null, };

export type ContentMetaSerializer = { start_time?: string | null, end_time?: string | null, };

export type ContentNodeSerializer = { id?: number | null, entry_id?: number | null, order_index?: number | null, name?: string | null, text?: string | null, ast?: any, html?: string | null, data?: JsonValue | null, template_id?: number | null, media_id?: number | null, parent_id?: number | null, embeds?: Array<MediaSerializer>, media?: MediaSerializer | null, };

export type ContentTagFacet = { name: string, slug: string, count: number, };

export type ContentTagSerializer = { id?: number | null, name?: string | null, slug?: string | null, };

export type ContentTypeSerializer = { id?: number | null, name?: string | null, slug?: string | null, order_index?: number | null, use_meta?: boolean | null, };

export type GroupMemberSerializer = { id: number, locale_code: string | null, locale_name: string | null, };

export type LocaleFacet = { code: string, name: string, count: number, };

export type MediaSerializer = { id?: number | null, alt?: string | null, title?: string | null, src?: string | null, filename?: string | null, path?: string | null, type?: string | null, width?: number | null, height?: number | null, size?: number, ast_line?: number | null, start_offset?: number | null, end_offset?: number | null, created_at?: string | null, processing_status?: string | null, variants?: Array<MediaVariantSerializer>, video_variants?: Array<MediaVideoVariantSerializer>, };

export type MediaVariantSerializer = { id: number, width: number, height: number, filename: string, };

export type MediaVideoVariantSerializer = { id: number, kind: string, profile: string, width: number, height: number, container: string, video_codec: string, audio_codec: string | null, filename: string, size: number, duration_ms: number | null, };

export type NodeSerializer = { "blocks": Array<ContentNodeSerializer> } | ContentNodeSerializer;
