// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MediaProgress = { phase: string, percent: number, };

export type SSELevel = "error" | "info" | "success" | "warning";

export type SSEMessage = { variance: SSELevel, text: string, media_id?: number, progress?: MediaProgress, };
