-- Upgrade databases created before runtime migrations shared the plugin journal.
ALTER TABLE public._plugin_migrations
ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE public._plugin_migrations
ADD COLUMN IF NOT EXISTS scope VARCHAR(16);

UPDATE public._plugin_migrations
SET
    scope = 'plugin'
WHERE
    scope IS NULL;

ALTER TABLE public._plugin_migrations
DROP CONSTRAINT IF EXISTS _plugin_migrations_pkey;

ALTER TABLE public._plugin_migrations
ALTER COLUMN plugin_id
DROP NOT NULL,
ALTER COLUMN scope
SET NOT NULL,
ALTER COLUMN id
SET NOT NULL;

ALTER TABLE public._plugin_migrations
ADD CONSTRAINT _plugin_migrations_pkey PRIMARY KEY (id);

ALTER TABLE public._plugin_migrations
DROP CONSTRAINT IF EXISTS plugin_migrations_scope_check;

ALTER TABLE public._plugin_migrations
ADD CONSTRAINT plugin_migrations_scope_check CHECK (
    (
        scope = 'runtime'
        AND plugin_id IS NULL
    )
    OR (
        scope = 'plugin'
        AND plugin_id IS NOT NULL
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS plugin_migrations_runtime_version_key ON public._plugin_migrations (version)
WHERE
    scope = 'runtime';

CREATE UNIQUE INDEX IF NOT EXISTS plugin_migrations_plugin_version_key ON public._plugin_migrations (plugin_id, version)
WHERE
    scope = 'plugin';
